version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file: postgres/database.conf
    environment:
      - APP_NAME=TecWeb
    links:
      - postgres:postgres
    expose:
      - "8080"

  react:
    build: ./react
    container_name: react
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - flask:flask
      - react:react

  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      - TZ=GMT
    env_file: postgres/database.conf
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
